"""
You want to add the numbers from 1 to 5 to a list, but the code below is not 
producing the expected result. How can you fix it?

numbers = []

for i in range(5):
    numbers.append(i)

print(numbers) # [0, 1, 2, 3, 4]
"""
numbers = []

for i in range(1, 6):
    numbers.append(i)

print(numbers) # [1, 2, 3, 4, 5]

"""
`range` objects in Python start at index 0 by default. With only one argument,
the number provided is the stop value. The stop value is exclusive, so it will
not be included in the sequence of numbers generated by the range object.

The stop value was previous at 5, which was why the output of the `numbers` 
list was `[0, 1, 2, 3, 4]`. 

We must change the start and stop values in order for numbers 1-5 
to be added to the list. This means using two arguments, with 1 as the start
value and 6 as the stop value.
"""
